### ISSUE TITLE
readlink syntax error on -f (Mac OS X)

### ISSUE THREAD

**Issue by mcandre** [jenv/jenv#113]
When I use jenv on Mac OS X, it attempts to use readlink with a `-f` option, which is unsupported in Mac OS X.

As a mitigation, users can install coreutils with Homebrew, which provides greadlink, an alternative to readlink.

Could we please have jenv not use the `-f` option on Mac OS X, or require greadlink, for a better out of the box experience?

**Comment by gcuisinier** [comment]
Strange, I will look how it can work on my OSX :)

**Comment by andrewflbarnes** [comment]
As far as I can see we no longer have reference to `readlink -f` either directly or indirectly through `resolve_link` functions.
