### ISSUE TITLE
JAVA_HOME is not defined correctly

### ISSUE THREAD

**Issue by icougil** [jenv/jenv#123]
Hi!
I'm using OS X El Capitan and I'm trying to use Crash (https://github.com/crashub), but it seems that it is returning that the JAVA_PATH it is not setting up:

> crash.sh
> Error: JAVA_HOME is not defined correctly.
>   We cannot execute /System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/bin/java

When I export the JAVA_HOME pointing to the default place when I have installed the JDK work perfectly. What can I do?

Best regards,

**Comment by kilsbo** [comment]
Got the same problem. This leads to maven to use wrong java version, for instance. Would be lovely with a fix for this.

Thank you.

**Comment by jangalinski** [comment]
Same problem here. Although "jenv init -" is executed, JAVA_HOME is not set.

**Comment by kflorence** [comment]
@jangalinski confirmed -- however I think the docs could use updating as it isn't very clear that you have to use the export plugin to get JAVA_HOME to update correctly.

**Comment by dkowis** [comment]
:+1: to updating documentation. I had to hunt for this to figure out how to know that the JAVA_HOME needed to be enabled via the export plugin. Otherwise, works just fine.

**Comment by dkowis** [comment]
I have found a problem using the export plugin with `system` java. There's no `.jenv/versions/system` directory, and so the JAVA_HOME is invalid, and it breaks a great deal of things. :(

**Comment by dkowis** [comment]
```
$  jenv local
1.7
$  echo $JAVA_HOME
/Users/dxk0875/.jenv/versions/1.8
```
I've found that the JAVA_HOME environment variable isn't being updated properly somehow. `jenv local` shows the right java version, as set by the .java-version file, but JAVA_HOME isn't being set correctly at all.

**Comment by gcuisinier** [comment]
do you have enabled the export plugin?

jenv enable-plugin export

**Comment by dkowis** [comment]
@gcuisinier Yep, it's enabled, and I tried unsetting it, and then entering the directory, or setting it manually. No luck.

```
$  cd .
$ echo $JAVA_HOME
/Users/dxk0875/.jenv/versions/1.8
$ unset JAVA_HOME
$ echo $JAVA_HOME

$ cd .
$ jenv local
1.7
$ echo $JAVA_HOME

$ jenv local 1.7
$ echo $JAVA_HOME

$ jenv local 1.8
$ echo $JAVA_HOME

$ jenv local 1.7
$ echo $JAVA_HOME

$
```

**Comment by gcuisinier** [comment]
Just to be sure : 
What's the output of 
```jenv doctor```

**Comment by dkowis** [comment]
Sorry it took me so long: 
```
$ jenv doctor
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
```

**Comment by dkowis** [comment]
Here's another `jenv doctor` output from a brand new shell:

```
$ jenv doctor
[OK]	JAVA_HOME variable probably set by jenv PROMPT
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
$ echo $JAVA_HOME
/Users/dxk0875/.jenv/versions/1.8
$ jenv shell 1.7
$ echo $JAVA_HOME
/Users/dxk0875/.jenv/versions/1.8
$ jenv doctor
[OK]	JAVA_HOME variable probably set by jenv PROMPT
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**Comment by turkmenf** [comment]
Is there a solution to this problem? I came by this one when trying to install maven...

**Comment by ramakrij** [comment]
I had this issue when I tried to install java 8 and I had java 7 already on my machine. After java 8 installation, by default system jdk is set to 8. Just use jenv to set the jdk version again (jenv global 1.8) and the java_home variable must now be updated from system to 1.8 path. This solved the issue for me.

**Comment by jayjlawrence** [comment]
The export plugin is not invoked as would be expected. It should be invoked when a Java version has been provided - typically via "cd" to the directory but also "jenv shell #.##" etc.

```bash
~/Projects > jenv version
1.6 (set by /Users/jaylawrence/.jenv/version)

~/Projects > echo $JAVA_HOME
/Users/jaylawrence/.jenv/versions/1.6

~/Projects > jenv shell 1.8
~/Projects > jenv version
**1.8** (set by JENV_VERSION environment variable)
~/Projects > echo $JAVA_HOME
/Users/jaylawrence/.jenv/versions/**1.6**

~/Projects > cd ../Projects
~/Projects > jenv version
**1.8** (set by JENV_VERSION environment variable)
~/Projects > echo $JAVA_HOME
/Users/jaylawrence/.jenv/versions/**1.8**
```

**Comment by andrewflbarnes** [comment]
Closing - this now works as expected.

**Comment by buryat** [comment]
hit the same issue, easiest was to symlink the system's java location

```
ln -s ~/Library/Java/JavaVirtualMachines/corretto-1.8.0_402/Contents/Home ~/.jenv/versions/system
