### ISSUE TITLE
Should honor $JAVA_HOME of the shell.

### ISSUE THREAD

**Issue by sterpe** [jenv/jenv#138]
I installed this a while back for some reason and just spent way too long trying to figure out why my change to $JAVA_HOME were not being honored by `java -version`.  

Anyway removing `jenv` completely.  I think honoring $JAVA_HOME is basic of a java version manager.

Perhaps you've fixed it since the version I was using.

**Comment by gcuisinier** [comment]
Hi,

You can try by enabling **export** plugins :
``jenv enable-plugin export```

**Comment by sterpe** [comment]
I think the point is that it should be default behavior.

**Comment by sterpe** [comment]
I mean suppose some project has a Makefile which sets JAVA_HOME to something and some one then tries to run a target on a machine with jenv installed...that will take hours to figure out what is wrong.  Honoring JAVA_HOME by default is the only sane behavior.

**Comment by soid** [comment]
+1 
I spent a few hours today figuring out what was wrong, and why jenv unsets JAVA_HOME

**Comment by andrewflbarnes** [comment]
Closing as stale. As a note most of the comments here are expected behaviour i.e. jenv manages the JAVA_HOME variable to reflect whatever the home folder is for the current instance of java that jenv (and therefore the user) is targettiing.
