### ISSUE TITLE
lein plugin fails to find java

### ISSUE THREAD

**Issue by vkz** [jenv/jenv#143]
``` sh
zerusski@:~$ jenv enable-plugin lein
lein plugin activated
zerusski@:~$ jenv enable-plugin export
export plugin already enabled
zerusski@:~$ lein
/usr/local/bin/lein: line 119: /Users/zerusski/.jenv/versions/oracle64-1.7.0.80/bin/java       : No such file or directory
zerusski@:~$ ls /Users/zerusski/.jenv/versions/oracle64-1.7.0.80/bin/java
/Users/zerusski/.jenv/versions/oracle64-1.7.0.80/bin/java
zerusski@:~$ jenv --version
jenv 0.4.4
zerusski@:~$ brew info jenv
jenv: stable 0.4.4, HEAD
Manage your Java environment
http://www.jenv.be
/usr/local/Cellar/jenv/0.4.4 (77 files, 65.2K) *
```

Disabling the lein plugin magically cures `lein`.

**Comment by gcuisinier** [comment]
I've reproduced the problem. Will be fixed in next version

**Comment by neverfox** [comment]
I can confirm this too when I tried to jack-in with CIDER with the lein plugin enabled.

**Comment by ShamilSungatov** [comment]
FYI this helps:
https://github.com/gcuisinier/jenv/issues/147#issuecomment-230703031

**Comment by shanipribadi** [comment]
the issue for me was this line
https://github.com/gcuisinier/jenv/blob/master/libexec/jenv-exec#L22
```
exportVariable(){   
   exportedValues="$exportedValues:$1"
   export $1="$2 $3 $4 $5 $6 $7 $8 $9"
}
```
removing the quotes from `export $1="$2  $3 $4 $5 $6 $7 $8 $9"` fixed the issue for me.
(but I end up just disabling lein plugin, and use export plugin instead with lein)

**Comment by ztellman** [comment]
I also had this issue with the latest `master`, and was able to fix it using @shanipribadi's change.  Can we get this, or something with the same effect, merged in?
