### ISSUE TITLE
Setting JENV in fish shell ?

### ISSUE THREAD

**Issue by iangregsondev** [jenv/jenv#152]
I seemed to have followed the instructions about the fish shell but still not working. Can anyone lend a hand ? Here is my doctor output

```
ian@ian-mint ~/.config/fish/functions [1]> jenv doctor                                                                             03:27:34
[OK]    No JAVA_HOME set
[ERROR] Java binary in path is not in the jenv shims.
[ERROR] Please check your path, or try using /path/to/java/home is not a valid path to java installation.
        PATH : /home/ian/.jenv/libexec:/home/ian/.jenv/shims:/home/ian/.jenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
[OK]    Jenv is correctly loaded
ian@ian-mint ~/.config/fish/functions>     
```                                                                                        03:27:36

Tried a rehash

```
jenv rehash                                                                                 03:29:51
No command 'hash' found, did you mean:
 Command 'bash' from package 'bash' (main)
 Command 'ash' from package 'ash' (universe)
 Command 'dash' from package 'dash' (main)
 Command 'wash' from package 'reaver' (universe)
 Command 'yash' from package 'yash' (universe)
 Command 'nash' from package 'lrslib' (universe)
 Command 'kash' from package 'kanif' (universe)
 Command 'rhash' from package 'rhash' (universe)
 Command 'sash' from package 'sash' (universe)
hash: command not found
- (line 1): begin; hash -r 
                   ^
from sourcing file -
        called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
        called on line 14 of file ~/.config/fish/functions/jenv.fish

in function “jenv”
        called on standard input
        with parameter list “rehash”

ian@ian-mint ~/.config/fish/functions [127]>   
```

**Comment by dkowis** [comment]
Of note, I don't have this problem on fish shell in OSX. It's only happening to me in Ubuntu.

I can jenv rehash with no problems on OSX, jenv is installed via brew, so I don't know if that's a significant difference or not.

**Comment by dkowis** [comment]
Looking at rbenv, in their rehash file:

https://github.com/rbenv/rbenv/blob/d0779fc8fb90fb7268d0ee858086e92bcd316787/libexec/rbenv-sh-rehash#L16-L23

```bash
case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
```

So I think all we need to do is make that small change, and then it's not an actual problem any more. I think it works, despite the really ugly error.

**Comment by dkowis** [comment]
Another problem with fish shell:

```
gitwork/theme-beep master> jenv enable-plugin export                    [825cdda]system1.8system
- (line 1): Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
begin; echo You may restart your session to activate  jenv export plugin echo export plugin activated && jenv rehash 
                                                                                                       ^
from sourcing file -
	called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
	called on line 14 of file ~/.config/fish/functions/jenv.fish

in function “jenv”
	called on standard input
	with parameter list “enable-plugin export”

source: Error while reading file “-”
```

probably just need to run through jenv and update it for fish. The project feels pretty old, sadly.

**Comment by andrewflbarnes** [comment]
Closing as stale but have merged the fish rehash PR
