### ISSUE TITLE
versions directory not created

### ISSUE THREAD

**Issue by rexgreen** [jenv/jenv#175]
`lizard@blade-stealth:~/.jenv$ jenv add /usr/lib/jvm/java-8-oracle
ln: failed to create symbolic link '/home/lizard/.jenv/versions/oracle64-1.8.0.144': No such file or directory
lizard@blade-stealth:~/.jenv$ ls
available-plugins  bin  completions  fish  libexec  LICENSE  README.md  shims
lizard@blade-stealth:~/.jenv$ mkdir versions
lizard@blade-stealth:~/.jenv$ jenv add /usr/lib/jvm/java-8-oracle
oracle64-1.8.0.144 added
1.8.0.144 added
1.8 added
`

**Comment by erstens** [comment]
+1

**Comment by ThomasKoppensteiner** [comment]
@rexgreen still an issue?

**Comment by rexgreen** [comment]
Not sure, have switched away from using jenv anyways... :(

**Comment by SpaceRangerWes** [comment]
@ThomasKoppensteiner it is still an issue

**Comment by onacit** [comment]
jenv 0.4.4 still has this issue.
I had to create `~/.jenv/` and `~/.jenv/versions`.

**Comment by mglaze** [comment]
@onacit has the right fix. 
I had to create both the `~./jenv`, `~./jenv/shims` and `~/.jenv/versions`
Now I can do the following: 
```
jenv add /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home
```
and I see the following: 
```
- oracle64-1.8.0.162 added
- 1.8.0.162 added
- 1.8 added
```

**Comment by binkley** [comment]
I see this as well, and the fix from @onacit works for me.

This seems like something `jenv` should do for itself.

**Comment by aarifsumra** [comment]
@onacit Thanks it works !

**Comment by marquiswang** [comment]
I reproduced this on Linux. Should be an easy fix.

**Comment by andrewflbarnes** [comment]
#404 fixes this to create the versions folder even if users haven't followed the steps in the readme to ensure that jenv is initialised prior to adding versions.
