### ISSUE TITLE
ZSH completion broken

### ISSUE THREAD

**Issue by az82** [jenv/jenv#196]
The ZSH completion was broken. The following construct was used to check if the number of words on the command line is 2:
```bash
if [ "${#words}" -eq 2 ]
```

`${#words}` returns the number of **characters** in `words` and not the number of words. This results in the following behaviour when pressing \<TAB\>:
```
$ jenv Usage: jenv completions <command> [arg1 arg2...]
 Usage: jenv completions <command> [arg1 arg2...]
  Usage: jenv completions <command> [arg1 arg2...]
  Usage: jenv completions <command> [arg1 arg2...]
```

PR request with fix: https://github.com/gcuisinier/jenv/pull/195

**Comment by bric3** [comment]
this issue should be closed ;)
