### ISSUE TITLE
jenv add: cd: too many arguments

### ISSUE THREAD

**Issue by Cloverii** [jenv/jenv#198]
I tried to add jdk 1.8 installed with Android Studio, but
`$ jenv add /Applications/Android\ Studio.app/Contents/jre/jdk/Contents/Home/
/usr/local/Cellar/jenv/0.4.4/libexec/libexec/jenv-add: line 51: cd: too many arguments`
But, when I tried to add another version of jdk, it succeeded.
`$ jenv add /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home`
So I considered it a problem caused by a space in path and tried those below, but  still the same error.
`$ jenv add "/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/"`
`$ jenv add '/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/'`

Then I found the content of line 51 in `jenv-add`: `$ cd $JENV_JAVAPATH`, but the output of `$ echo JENV_JAVAPATH` is a blank line.

**Comment by rakesh1988** [comment]
any solution for this problem?
trying to add android studio's jdk to jenv to avoid additional java installations and i have same problem

**Comment by gkylafas** [comment]
I worked around it by making a symbolic link
```
$ cd /Library/Java/JavaVirtualMachines
$ sudo ln -s /Applications/Android\ Studio.app/Contents/jre/jdk jdk-android-studio
$ jenv add jdk-android-studio/Contents/Home
```

**Comment by andrewflbarnes** [comment]
Fixed at some point, paths with spaces are now handled correctly:
```
$ jenv add ~/test\ it/openjdk21/Contents/Home/
 openjdk64-21.0.2 already present, skip installation
 21.0.2 already present, skip installation
 21.0 already present, skip installation
 21 already present, skip installation
```
