### ISSUE TITLE
Detect and alias graalvm

### ISSUE THREAD

**Issue by Milyardo** [jenv/jenv#199]
With graal 1.0 released it would be nice to detect GraalVM in `java -version` allowing users to swap between jvms with a standard compiler and graal/truffle and have it detected as something other than `other64`.

**Comment by bygui86** [comment]
+1

**Comment by lmiranda** [comment]
+1

**Comment by andrewflbarnes** [comment]
Stale, working.
```
$ jenv versions | grep graal
  graal-16
  graal-16.0
  graal-16.0.1
  graal-17
  graalvm64-17.0.4
```
