### ISSUE TITLE
Installing from brew does not create the ~/.jenv/versions directory. It should.

### ISSUE THREAD

**Issue by doctorpangloss** [jenv/jenv#207]
This critical error means that `jenv` doesn't work on macOS out of the box.

**Comment by szaske** [comment]
I found this same problem.  Install on Mac OS does not work

**Comment by glawrence** [comment]
Same for me. I installed Java 8 view brew and then Java 10 and then jenv and now jenv does not work, which is a poor out of the box experience, however a simple `mkdir -p ~/.env/versions` fixes this

**Comment by watonyweng** [comment]
`echo 'eval "$(jenv init -)"' >> ~/.bash_profile && exec $SHELL -l `, please read [jenv init](https://github.com/gcuisinier/jenv/blob/master/libexec/jenv-init#L74)

**Comment by toddcscar** [comment]
Same experience for me.  With the ensuing jdk version anarchy, this useful tool is greatly needed.
At least put a note on the install page.

**Comment by rbobin** [comment]
@glawrence thank you for the solution. Please fix your `.env` to be `.jenv`

**Comment by andrewflbarnes** [comment]
#404 fixes this to create the versions folder even if users haven't followed the steps in the readme to ensure that jenv is initialised prior to adding versions.
