### ISSUE TITLE
List actual installation directory for each version

### ISSUE THREAD

**Issue by udalrich** [jenv/jenv#210]
I recently needed to find a file in my installed JDK that jenv was not mirroring (src.zip).  jenv works so well that I had forgotten where the JDK was installed.  So I tried to ask jenv where the source installation was.  Either that option does not exist or it is not documented well enough for me to find it.

I was hoping to do something like

    $ jenv versions --source
    10.0   /Library/Java/JDK/10.0
    1.8     /Library/Java/JKD/1.8

**Comment by gcuisinier** [comment]
There is command that may help you :

```
jenv versions --verbose
````

**Comment by udalrich** [comment]
It would be good to document this.

```
$ jenv help versions 
Usage: jenv versions [--bare]

Lists all Java versions found in `$JENV_ROOT/versions/*'.
```

Using jenv 0.5.2
