### ISSUE TITLE
JAVA_HOME variable change

### ISSUE THREAD

**Issue by vsethi13** [jenv/jenv#214]
Not sure if it's a bug or an intended behavior (in which case I'd like to raise a feature request 🙏 )
When you change shell's java version by issuing the following command:
`jenv shell <version>`
... the JAVA_HOME variable remains unchanged. It'd be great if changing versions changed the JAVA_HOME variable too.

Here's a screenshot of the command chain to validate my claim:
<img width="507" alt="screen shot 2018-09-18 at 2 44 35 pm" src="https://user-images.githubusercontent.com/8803605/45677396-b0567000-bb51-11e8-9879-005ff9c1b71d.png">

**Comment by gcuisinier** [comment]
Indeed !

**Comment by andrewflbarnes** [comment]
This works :)
