### ISSUE TITLE
Not recognizing java 11

### ISSUE THREAD

**Issue by kevwil** [jenv/jenv#215]
With jenv 0.4.4 installed via Homebrew:

```
$ brew cask info java
java: 11,28:55eed80b163941c8885ad9298e6d786a
https://www.oracle.com/technetwork/java/javase/overview/index.html
/usr/local/Caskroom/java/11,28:55eed80b163941c8885ad9298e6d786a (166.6MB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/java.rb
==> Name
Java Standard Edition Development Kit
==> Artifacts
JDK 11.pkg (Pkg)
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing java means you have AGREED to the license at
  https://www.oracle.com/technetwork/java/javase/terms/license/javase-license.html

$ /usr/libexec/java_home --exec java -version
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)

$ jenv versions
  system
* 1.8 (set by /Users/boringusername/.jenv/version)
  1.8.0.181
  oracle64-1.8.0.181
```

I have java8 installed via Homebrew as well, and that's the only non-system version that jenv picks up. I updated the Homebrew java install this morning which upgraded from java 10.0.0.2 to 11. Previously, jenv was seeing the 10.0.0.2 version.

**Comment by mihaicris** [comment]
I am not sure if this feature is included. I think you have to add java 11 manually:
`jenv add /Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/`

I also would like to have at least a discovery command to search for all java versions installed on my system, something like:

```
jenv discover
/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/
/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/
```

**Comment by kevwil** [comment]
Actually I see that this morning jenv shows the jdk-11 entry that wasn't there yesterday. I didn't do anything to add it. Perhaps I didn't reload my shell as correctly as I thought I did.

**Comment by gcuisinier** [comment]
At this time, jenv will not discover automatically new java version installed.
So effectively, you have to run 
`jenv add /Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/`


Adding jenv discovery feature should be interesting, but it have to deal with all "OS/Package management" for that

**Comment by mb-3000** [comment]
this worked for me, remember to delete the other older JVM's you might have had.

I would have thought the `jenv rehash` could look for the usual suspects or scan the output of the `/usr/libexec/javahome -V` call to find all the registered JVM's on the platform.

**Comment by doctorpangloss** [comment]
@kevwil @mb-3000 

I've written pretty clear instructions for macOS on my maintained fork:

https://github.com/hiddenswitch/jenv

**Comment by andrewflbarnes** [comment]
closing as stale - a separate issue has been raised for discovery.
