### ISSUE TITLE
Support gcj JDK

### ISSUE THREAD

**Issue by gcuisinier** [jenv/jenv#22]
At this time, adding a xgc JDK create a "other" alias name.
A more specific name should be generated

vagrant@vagrant-debian-wheezy-64:~$ /usr/lib/jvm/java-gcj/bin/java -version
java version "1.5.0"
gij (GNU libgcj) version 4.7.2

**Comment by andrewflbarnes** [comment]
Given the final release for thisi was 6 years ago will close as verrrrrry stale.

Versions can always be manually added to jenv with `java add <alias> /path/to/java/home`
