### ISSUE TITLE
Newly maintained fork

### ISSUE THREAD

**Issue by doctorpangloss** [jenv/jenv#228]
I've taken care of some of the pull requests and tuned up the README significantly to better support macOS. If you found this project via Google, you can reach this newly maintained fork here:

https://github.com/hiddenswitch/jenv

There are a lot of untested features in this repository. I did my best to actually test everything that appears in my fork's README.

**Comment by Tmarty** [comment]
@doctorpangloss do you want to make a pull request with your changes?

**Comment by gcuisinier** [comment]
@Tmarty @doctorpangloss I've already merge all your work from the fork.

The question is more for the future, do you want to continue on the fork ? Or to contribute here as maintainer ?
As you can see, I've already move the @gcuisinier/jenv repository to the "jenv" organization.

**Comment by madumlao** [comment]
I'm pleasantly surprised to see we've received updates. Haven't seen this active in a while :)

**Comment by doctorpangloss** [comment]
I will contribute to the main repository!

**Comment by gcuisinier** [comment]
Great ! 👍
