### ISSUE TITLE
zsh autocd not working after installation

### ISSUE THREAD

**Issue by sebastienfr** [jenv/jenv#234]
After brew updated *jenv* to 0.5.0, my export plugin (for maven) was not working anymore but uninstall/install fixed it (thanks to #233 tip).

I also noticed `zsh autocd` was not working anymore. Setting option `setopt autocd` in the terminal was fine but was not taken into account in the zshrc file. 
To fix the issue I has to put the instruction after the` jenv init -`part. 

Here after is the extract of my zshrc : 
```
# init jenv
if which jenv > /dev/null; then eval "$(jenv init -)"; fi

# zsh options
setopt autocd
```
And the result of my `jenv init -` :
```
export PATH="/Users/seb/.jenv/shims:${PATH}"
export JENV_SHELL=zsh
export JENV_LOADED=1
unset JAVA_HOME
source '/usr/local/Cellar/jenv/0.5.1/libexec/libexec/../completions/jenv.zsh'
jenv rehash 2>/dev/null
source "/Users/seb/.jenv/plugins/export/etc/jenv.d/init/export_jenv_hook.zsh"
jenv() {
  typeset command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  enable-plugin|rehash|shell|shell-options)
    eval `jenv "sh-$command" "$@"`;;
  *)
    command jenv "$command" "$@";;
  esac
}
```

**Comment by sebastienfr** [comment]
Btw, `autocd` is a zsh feature that allows to change directory without the `cd` command.

Ex : `../upperdir` instead of `cd ../upperdir`

When `autocd` is not working, then the shell tries to interpret the command as a executable and you get an error : `zsh: permission denied: ../upperdir`

Adding the following option after the `jenv init` part fixes the issue temporarily.

         # zsh options
         setopt autocd

**Comment by bric3** [comment]
Got the same issue, but I'm loosing other options as well :

- `autocd`
- `extendedglob`
- `nonomatch`
- `pushdignoredups`
- `pushdminus`

The issue seems related to how export plugin works : 

```
~ jenv disable-plugin export
You may restart your session for removing the jenv export plugin
export disabled
 ~ zsh -i -c "setopt"
alwaystoend
autocd
autopushd
nobeep
nocaseglob
combiningchars
completeinword
correctall
extendedglob
extendedhistory
noflowcontrol
histexpiredupsfirst
histignoredups
histignorespace
histverify
incappendhistory
interactive
interactivecomments
longlistjobs
monitor
nonomatch
promptsubst
pushdignoredups
pushdminus
zle
 ~ jenv enable-plugin export
You may restart your session to activate jenv export plugin echo export plugin activated
 ~ zsh -i -c "setopt"
alwaystoend
autopushd
nobeep
nocaseglob
combiningchars
completeinword
correctall
extendedhistory
noflowcontrol
histexpiredupsfirst
histignoredups
histignorespace
histverify
incappendhistory
interactive
interactivecomments
longlistjobs
monitor
promptsubst
zle
 ~
```

**Comment by bric3** [comment]
The issue appear after this line :

https://github.com/jenv/jenv/blob/33e367b1c2ec40afd5956c1489340e73a56979b3/available-plugins/export/etc/jenv.d/init/export_jenv_hook.zsh#L1

**Comment by bric3** [comment]
So this is related to this change https://github.com/jenv/jenv/commit/dceefcd9cae4891cc1e3ed383954e78fc30c669b made by @madumlao.

After reading what `emulate` is for, it seems weirdly placed because it affects the whole shell.
