### ISSUE TITLE
Please consider adding an integration with visual studio code

### ISSUE THREAD

**Issue by juanmbellini** [jenv/jenv#252]
Visual Studio Code has an extension for Java, which does not integrate well with jEnv. You need to specify in a configuration file which the java home path, which is not the best thing to do. Also you can set the java version setting the JDK_HOME or the JAVA_HOME variables.
Maybe, if jEnv sets any of those variables, the integration will be performed easily.

Check more info in https://marketplace.visualstudio.com/items?itemName=redhat.java

**Comment by gcuisinier** [comment]
Seems interesting.
I will look at this, but not before July. I am quite busy for the moment

**Comment by hermitmaster** [comment]
Enabling the export plugin solves this problem. Can be closed.
