### ISSUE TITLE
MacOS Installed Java versions path issue

### ISSUE THREAD

**Issue by asthinasthi** [jenv/jenv#253]
I had to use the following variants to successfully add Java8 & Java 11

## Java 11
`jenv add /Library/Java/JavaVirtualMachines/jdk-11.0.3.jdk/Contents/Home/`

## Java 8
`jenv add /Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/jre`

**Comment by bric3** [comment]
@asthinasthi Java 11 do not ship  the JRE anymore, JDK and JRE are marged. (see [release notes](https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html#Removed)).
But in my experience `jenv add /Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/` should work, unless the installation didn't actually install a JDK but the JRE only, that's weird, but possible with Java 8 I think.

**Comment by andrewflbarnes** [comment]
closing as stale
