### ISSUE TITLE
Can't load jenv in zsh on OSX

### ISSUE THREAD

**Issue by BenManifold** [jenv/jenv#259]
ZSH is unable to evaluate the output of "jenv init -".

Attempting to run this via source ~/.zshrc always produces an error of "zsh: parse error near `then'"

**Comment by gsaslis** [comment]
hmm are you sure you have `eval "$(jenv init -)"` and not just `jenv init -` in your `.zshrc` ?

`jenv init -` expands to some bash script that does have a `then` init, so that would explain your error message.

**Comment by hermitmaster** [comment]
`echo ". <(jenv init -)" >> ~/.zshrc` will solve your issues.
