### ISSUE TITLE
upgrading from 0.4.4 to 0.5.2 did not upgrade exec scripts in shims directory

### ISSUE THREAD

**Issue by toddcscar** [jenv/jenv#283]
After upgrading from 0.4.4 to 0.5.2, executing any java command results in the following:

```
/Users/*****/.jenv/shims/java: line 21: /usr/local/Cellar/jenv/0.4.4/libexec/libexec/jenv: No such file or directory
```
What is the command to replace the shims with the correct version?

**Comment by toddcscar** [comment]
i somehow fixed it by removing shims directory and running jenv doctor.  I am not clear on exact steps fixed the issue.

**Comment by benja83** [comment]
Removing the shims directory fix the issue for me. Running jenv doctor told me that everything was fine.

**Comment by TheCycoONE** [comment]
I also hit this on an upgrade
