### ISSUE TITLE
Website is insecure, according to my browser

### ISSUE THREAD

**Issue by binkley** [jenv/jenv#286]
![image](https://user-images.githubusercontent.com/186421/78563181-2bd54c00-77e0-11ea-9379-7879eea05526.png)

I see when visiting `jenv.be` that my browser complains that it is an insecure site.  I understand that setting up certificate security can be challenging.

Is this something to be addressed?

**Comment by gcuisinier** [comment]
Jenv website was accessible from both http (unsecure) and https (secure).

 I enforce https now. Should be better :)

**Comment by binkley** [comment]
Looks great now on the browsers I tried.  Thanks!
