### ISSUE TITLE
jenv and git on enterprise

### ISSUE THREAD

**Issue by asantosca** [jenv/jenv#298]
we are putting .java-version in git, which is great, but also causing us problems.
one developer uses 1.8 commits/pushes the .java-version; the next developer pulls it, but then jenv doesn't recognize "1.8", only "1.8.0.252".
The second developer has to either keep track not to check .java-version in, or check it in and pass the bucket to the next one.
Also, everyone having the exact same jdk version is not realistic.
Would it be possible for jenv to recognize "1.8.0.252" as "1.8", or allow us to add an alias?
Would there something we could do on our machines so jenv would understand it, like creating a simlink between 1.8 and 1.8.0.252?

**Comment by gcuisinier** [comment]
Hello,

Not sure to understand.
If both developer add JDK 1.8, but with different minor version, they should have multiple alias added, and one should be "1.8" normally no ?

**Comment by asantosca** [comment]
The .java-version has "1.8" in it.
On my machine, the java versions are 
Matching Java Virtual Machines (4):
    14.0.1, x86_64:	"AdoptOpenJDK 14"	/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home
    12.0.2, x86_64:	"AdoptOpenJDK 12"	/Library/Java/JavaVirtualMachines/adoptopenjdk-12.jdk/Contents/Home
    11.0.7, x86_64:	"AdoptOpenJDK 11"	/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
    1.8.0_252, x86_64:	"AdoptOpenJDK 8"	/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home

my jenv versions are 
  system
  1.8.0.252
* 11.0.7 (set by /Users/local/.jenv/version)
  12
  12.0.2
  Home
  openjdk64-1.8.0.252
  openjdk64-11.0.7
  openjdk64-12.0.2

When I check out the project, the .java-version is "1.8" and my java is "1.8.0.252"
I can't run the shims because jenv can't find 1.8, only 1.8.0.252.

Is there a way jenv can see "1.8" in .java-version but still use my 1.8.0.252?

**Comment by hermitmaster** [comment]
`jenv add` should have created the 1.8 alias automatically.

**Comment by asantosca** [comment]
The root of this issue is that `jenv` wasn't properly cleaning past java versions.
In my case, I had added and removed Oracle's jdk and installed open jdk.
It would be nice if `jenv doctor` would remove stale links.
Thank you for `jenv`. It is a tool I use every day.
