### ISSUE TITLE
Enhance `jenv versions` by showing the full path to each version

### ISSUE THREAD

**Issue by howthatdo** [jenv/jenv#300]
I've got multiple versions of the JDK installed - sometimes both an OpenJDK and Oracle implementation of the same version. When I use `jenv versions`, it would be nice to see the full path to the JDK in order to easily determine which is which.

**Comment by slawekjaranowski** [comment]
did you try:
`jenv versions --verbose`

**Comment by howthatdo** [comment]
That’s great. Thanks!
