### ISSUE TITLE
Release please?

### ISSUE THREAD

**Issue by hermitmaster** [jenv/jenv#304]
Merge #225 and cut a release please. It would help those of us using fish shell and brew a great deal. Currently, the only way to get jenv to work with fish is to install directly from repo or `brew install jenv --HEAD` Thanks!

**Comment by gcuisinier** [comment]
Will try to do that soon !
Sorry for the delay #needMoreTime

**Comment by hermitmaster** [comment]
I’m happy to volunteer if you need maintenance help.

**Comment by hermitmaster** [comment]
Thank you @gcuisinier!

**Comment by gcuisinier** [comment]
@hermitmaster any help is always welcome :)
