### ISSUE TITLE
MY JAVA VERSION IS NOT CHANGING EVEN AFTER SETTING GLOBAL WITH JV KINDLY HELP

### ISSUE THREAD

**Issue by vjkhere** [jenv/jenv#305]
<img width="928" alt="the problem" src="https://user-images.githubusercontent.com/31820050/90622274-8244a380-e232-11ea-8a65-cdb4068f6653.png">

**Comment by vjkhere** [comment]
I AM ATTACHING MY JENV DOCTOR HERE 
<img width="1302" alt="thefinalproblem" src="https://user-images.githubusercontent.com/31820050/90622428-b28c4200-e232-11ea-8409-2eadfb91a90f.png">

**Comment by mikesaurus** [comment]
I personally haven't seen this, but have you tried running `jenv enable-plugin export`?  (reference: https://developer.bring.com/blog/configuring-jenv-the-right-way/)

**Comment by zhiqiangZHAO** [comment]
I have the same issue. After I run the last output command of "jenv doctor", and source the shell rc file, it works.

**Comment by andrewflbarnes** [comment]
Per the responses and docs you need to ensure the below have been added to your ~/.zshrc or equivalent
```
# if you installed from source with git also include the below
# export PATH="$HOME/~/.jenv/bin:$PATH"
eval "$(jenv init -)"
```

Then in a new shell (or `exec $SHELL -l`)
```bash
jenv enable-plugin export
```

And finally start/exec a new shelll again (will raise a change so this final step isn't needed). This should result in jenv being fully loaded and configured.
