### ISSUE TITLE
JAVA_HOME is not being set

### ISSUE THREAD

**Issue by aschuhl** [jenv/jenv#324]
On macos 11.2.3

> java -version

```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
Eclipse OpenJ9 VM (build openj9-0.24.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20210120_839 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - ab07c6a8fd based on jdk8u282-b08)
```

> jenv version

`1.8 (set by /Users/aschuhl/.jenv/version)`

> jenv versions

```
  system
* 1.8 (set by /Users/aschuhl/.jenv/version)
  1.8.0.282
  11
  11.0
  11.0.10
  9
  ibm64-1.8.0.282
  ibm64-11.0.10
  openjdk64-1.8.0.282
  openjdk64-9
```

Using zsh with oh-my-zsh and powerlevel10k

I have added 

> export PATH="$HOME/.jenv/bin:$PATH"
> eval "$(jenv init -)"

to by profile and have even run it in the current shell to test.

> echo $HOME/.jenv/bin:$PATH
```
/Users/aschuhl/.jenv/bin:/Users/aschuhl/.jenv/shims:/Users/aschuhl/.jenv/bin:/Users/aschuhl/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

> echo $JAVA_HOME

```
﻿
```

Any ideas?

**Comment by aschuhl** [comment]
I found the issue in the readme. I needed to run: 

> jenv enable-plugin export

I noticed that https://www.jenv.be/ doesn't contain this information though under the installation section.

**Comment by EasyG0ing1** [comment]
@aschuhl 
> I found the issue in the readme. I needed to run:
> 
> > jenv enable-plugin export

Thank you for this, it solved my problem.

**Comment by andrewflbarnes** [comment]
I've updated the website to include enabling the export plugin :)
