### ISSUE TITLE
Can I remv

### ISSUE THREAD

**Issue by DanteCY** [jenv/jenv#331]
hcydeMacBook-Pro-3:JavaVirtualMachines hcy$ jenv add /Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home/
oracle64-12.0.2 added
12.0.2 added
12.0 added
12 added

when I run a add command.
4 version will list in jenv versions
but they are the same jdk。
So.Can I choose which one show in the version list？

**Comment by andrewflbarnes** [comment]
This is intended  and allows you to have multiple major versions of the same JDK, or even different distriutions with the same version, available through jenv. You can choose any version as you say.
