### ISSUE TITLE
jenv add bug ," " in path

### ISSUE THREAD

**Issue by li-keguo** [jenv/jenv#332]
jenv add /Applications/IntelliJ IDEA.app/Contents/jbr/Contents/Home/

output:
Warning : jenv add alias path/to/java_home is deprecated.
Please prefer to let jenv generate unique alias name by using

    $ jenv add path/to/java_home

/opt/homebrew/Cellar/jenv/0.5.4/libexec/libexec/jenv-add: line 56: cd: IDEA.app/Contents/jbr/Contents/Home/: No such file or directory

**Comment by gcuisinier** [comment]
It's due to the "space" in the IntelliJ IDEA.app, that make jenv think it's two parameter.
Try with

jenv add "/Applications/IntelliJ IDEA.app/Contents/jbr/Contents/Home/"
