### ISSUE TITLE
No java_home set with pre-installed java versions

### ISSUE THREAD

**Issue by NataliiaAlokhina** [jenv/jenv#336]
Hi! Maybe easy question, but still... 
I had java 17 installed by brew, and then i installed jenv and did `jenv add`, also did enabled export plugin and still java_home is not set. 
```
jenv doctor
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded
```
How can i fix this? I tried `brew reinstall openjdk` and still have no java_home

**Comment by andrewflbarnes** [comment]
JAVA_HOME only gets set when you specify a non-system version set (either with `jenv global`, `jenv local` or `jenv shell` - the default if none of these are set is `system`).

To see what versions you have run `jenv versions`, to see what version is set, and what is setting it, run `jenv version`.

If you run say `jenv shell 17` (set the version of java in the current shell to `17`, the one you added) and run `jenv doctor` again it will show the JAVA_HOME has been set. You can run `jenv info <java cmd>` to see what the JAVA_HOME will be and which binary will be executed - thiis will be the version you added, but symlinked into `~/.jenv` e.g.
```
$ jenv version
system (set by /Users/andrew.barnes/.jenv/version)

$ jenv doctor
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded

$ jenv shell 17

$ jenv version
17 (set by JENV_VERSION environment variable)

$ jenv doctor
[OK]	JAVA_HOME variable probably set by jenv PROMPT
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded

$ jenv info java
Jenv will exec : /Users/andrew.barnes/.jenv/versions/17/bin/java
Exported variables :
  JAVA_HOME=/Users/andrew.barnes/.jenv/versions/17
```
