### ISSUE TITLE
~/.jenv not exiting on macOs

### ISSUE THREAD

**Issue by jpralle** [jenv/jenv#348]
Hi there,

I did a fresh install on my MacBook (macOs BigSur 11.6.1) using homevrew, with two existing JDKs already installed. After the installation it looks like this:
```
jpralle@PC ~ % jenv versions
* system (set by /Users/jpralle/.jenv/version)
jpralle@PC ~ % java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

Looks basically good, JAVA_HOME initially pointed to the OpenJDK 1.8. But ~/.jenv does not exist. When I now try to add my JDK 16, it does not work:
```
jpralle@PC ~ % jenv add /Library/Java/JavaVirtualMachines/temurin-16.jdk/Contents/Home
ln: /Users/jpralle/.jenv/versions/openjdk64-16.0.2: No such file or directory
```

When I do the following it works:
```
jpralle@PC ~ % mkdir .jenv
jpralle@PC ~ % mkdir .jenv/versions
jpralle@PC ~ % jenv add /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
openjdk64-1.8.0.292 added
1.8.0.292 added
1.8 added
jpralle@PC ~ % jenv versions
* system (set by /Users/jpralle/.jenv/version)
  1.8
  1.8.0.292
  openjdk64-1.8.0.292
jpralle@PC ~ % jenv add /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
 openjdk64-1.8.0.292 already present, skip installation
 1.8.0.292 already present, skip installation
 1.8 already present, skip installation
jpralle@PC ~ % jenv add /Library/Java/JavaVirtualMachines/temurin-16.jdk/Contents/Home
openjdk64-16.0.2 added
16.0.2 added
16.0 added
16 added
jpralle@PC ~ % jenv versions
* system (set by /Users/jpralle/.jenv/version)
  1.8
  1.8.0.292
  16
  16.0
  16.0.2
  openjdk64-1.8.0.292
  openjdk64-16.0.2
```
Not sure if "system" will be working, but for now it looks good. I'll check whether it works correctly now, but so far it looks as it will work. Just wanted to let you know there seems to be something of with the macOs installer.

**Comment by jpralle** [comment]
Okay, I regret to add that it does now work. When I open an new terminal either from Finder of PathFinder, it does not respect the JDK version set in the respective folder inside .java-version. Also it does not work in IntelliJ, which might not be your thing, but would be cool, if it does. Not sure what additional information I can provide on this, just let me know.

**Comment by gcuisinier** [comment]
Can you execute 

`jenv doctor`

**Comment by marquiswang** [comment]
@jpralle Did you ever get it working?

Simply installing `jenv` via Homebrew isn't sufficient. Homebrew will not add jenv to your shell profiles, or configure it to export JAVA_HOME.

It sounds like you need to run:

```
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(jenv init -)"' >> ~/.bash_profile
exec $SHELL -l
jenv enable-plugin export
```
Or, if you're using zsh
```
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.zshrc
echo 'eval "$(jenv init -)"' >> ~/.zshrc
exec $SHELL -l
jenv enable-plugin export
```

**Comment by jpralle** [comment]
Hi,

first of all sorry for reply that immensly late. The notifications for the replys did arrive very late, after I (almost) forgot about jenv and then getting back to it...

I did add the additions to my .zshrc and now it works, even in IntelliJ 😀  jenv doctor now also works. Thanks a lot!
