### ISSUE TITLE
Possibility of a 0.5.5 release

### ISSUE THREAD

**Issue by lbergelson** [jenv/jenv#361]
Would a new release be possible so that ed864e49d84ab939bb3e3b3ffe202632de641135 can be made available through brew?

**Comment by marquiswang** [comment]
Released!

**Comment by obfischer** [comment]
Is there a changelog available?

Am 04.06.22 um 05:26 schrieb Marquis Wang:

**Comment by lbergelson** [comment]
@marquiswang Thank you!
