### ISSUE TITLE
Export plugin in fish now outputs /usr/local/bin/jenv after every shell command

### ISSUE THREAD

**Issue by vincentjames501** [jenv/jenv#364]
This appears to have been broken by https://github.com/jenv/jenv/pull/321 .

For example if I run:

```
$ command -s jenv                                                                                                                                                                                                       12:28:32
/usr/local/bin/jenv
```

You can see that output. I think it would be better to just do something like `if not type -q jenv` CC @0az . Thoughts?

**Comment by andrewflbarnes** [comment]
Closing as this has been [addressed](https://github.com/jenv/jenv/blob/705a705aa441fb3989d584797ef959e5190064b9/available-plugins/export/etc/jenv.d/init/export_jenv_hook.fish#L3) and is available in the latest verion. Please re-open if still an issue.
