### ISSUE TITLE
It can't detect Zulu JDK!

### ISSUE THREAD

**Issue by euporiacosmos** [jenv/jenv#367]
[https://www.azul.com/](url)
`jenv list`

**Comment by pe** [comment]
Are you using the newest version? (0.5.5 for 2022-06-04) Support was added with 1fd8ba9885f1b8a3932c5c17ca2213ec4093349a

And to my knowledge, there is no `list`-Command in jEnv?

**Comment by davewichers** [comment]
I was able to add a bunch of different azul JDKs today using jenv. I'd close this as a non-issue.
