### ISSUE TITLE
Release new version of jenv

### ISSUE THREAD

**Issue by mdedetrich** [jenv/jenv#379]
Would it be possible to make a new release of jenv since https://github.com/jenv/jenv/pull/365 was merged? Without it there are still problems with using jenv on fish.

**Comment by tzahari** [comment]
Yes, please! 🙏

**Comment by tzahari** [comment]
@mdedetrich you can install the HEAD version of jenv...
```
brew uninstall jenv
brew install jenv --HEAD
```
Don't forget to restart the terminal session...

**Comment by mdedetrich** [comment]
> @mdedetrich you can install the HEAD version of jenv...
> ```
> brew uninstall jenv
> brew install jenv --HEAD
> ```
> Don't forget to restart the terminal session...

Thanks!

A release should be made, nevertheless. I am getting the impression that the maintainers aren't active anymore

**Comment by gcuisinier** [comment]
You are not far from reality 😅

As I have issue to find time, I already try multiple to find new maintainers.
But seems that they had the same problem than me.

I will try to take time for new Reelase if needed.

**Comment by mdedetrich** [comment]
@gcuisinier Thanks for finding the time to respond, I also maintain multiple OS projects so I know how it feels. Note that due to the workaround that @tzahari posted (which I wasn't aware of, I remember that at least some time ago int he past doing brew installs from head was quite cumbersome) its not that critical for me to make a release but I suspect that in doing so you would reduce future potential questions for those using fish

> As I have issue to find time, I already try multiple to find new maintainers.
But seems that they had the same problem than me.

Is the release process documented somewhere? If so I can have a look and if its not too complicated I may consider helping out by volunteering to do releases.

**Comment by marquiswang** [comment]
I'll make a release today.

The release process is *relatively* straightforward, though I don't have access to the credentials to run the release workflows so I had to do it manually last time.
