### ISSUE TITLE
Error when trying to add openjdk 11 installed with brew on MAC with M1 pro chip

### ISSUE THREAD

**Issue by pablichjenkov** [jenv/jenv#382]
When using `jenv add $JAVA_HOME` 
To add the path of openjdk11 installed with brew I get the bellow error:
**/opt/homebrew/Cellar/openjdk@11/11.0.17/bin is not a valid path to java installation**

**Comment by pablichjenkov** [comment]
This is my jenv doctor output:

_pvaldesrccl.com@FW1G2DQ96K ~ % jenv doctor
[OK]	No JAVA_HOME set
[ERROR]	Java binary in path is not in the jenv shims.
[ERROR]	Please check your path, or try using /path/to/java/home is not a valid path to java installation.
	PATH : /opt/homebrew/Cellar/jenv/0.5.5_2/libexec/libexec:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/homebrew/bin:/opt/homebrew/Cellar/openjdk@11/11.0.17/bin
[ERROR]	Jenv is not loaded in your zsh
[ERROR]	To fix : 	echo eval "$(jenv init -)" >> /Users/pvaldesrccl.com/.zshrc_

**Comment by mdedetrich** [comment]
You are adding the wrong directory, you should be doing something like

```
jenv add /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home
```

**Comment by pablichjenkov** [comment]
Ah ok, kinda late. I started using a different approach not jenv, but thanks for answering.
