### ISSUE TITLE
Run init command in a smarter way

### ISSUE THREAD

**Issue by jlosito** [jenv/jenv#387]
# Summary

When trying to add a new version of java to jenv via `jenv add /path/to/java`, the command will fail unless the path to `~/.jenv/versions` does not already exist. I understand that the `jenv init` command is supposed to take care of this, but it would be nice if jenv was a little bit smarter and knew it needed yo create it on its own rather than me explicitly telling it to do so.

## How to reproduce
```
% jenv add /opt/homebrew/opt/openjdk/
ln: /Users/myuser/.jenv/versions/openjdk64-19.0.2: No such file or directory
% mkdir -p ~/.jenv/versions
% jenv add /opt/homebrew/opt/openjdk/
openjdk64-19.0.2 added
19.0.2 added
19.0 added
 19.0.2 already present, skip installation
```

## Expected Behavior

I expect jenv to check if the `~/.jenv/versions` path exists prior to trying to add the java versions. If the path does not exist, please create it for me via a `jenv init` or whatever other mechanism it should rather than having to issue the command, then try to add the java versions.

**Comment by andrewflbarnes** [comment]
Fixed by #404
