### ISSUE TITLE
jenv does not support the `gu` command for GraalVM

### ISSUE THREAD

**Issue by hgschmie** [jenv/jenv#397]
GraalVM ships with the `gu` command to install additional components (such as native-image). While jenv installs shims for all the other binaries, it does not for `gu`.

**Comment by kworkbee** [comment]
Same here too

**Comment by andrewflbarnes** [comment]
This seems to be working for me
```
[root@3c1fdc0d8539 /]# jenv add /usr/lib/jvm/graalvm-ce-java11-22.3.3/
graalvm64-11.0.20 added
11.0.20 added
...
[root@3c1fdc0d8539 /]# jenv shell 11.0.20
[root@3c1fdc0d8539 /]# gu
GraalVM Component Updater v2.0.0
```

jenv doesn't discriminate about what it creates shims for, it just looks in the bin folder for the version you have specified and creates a shim for everything in there.

What commands are your trying and output are you seeing? What version of graal are you trying with? If you check `jenv version` and  `jenv versions --verbose` are you definitely using a version which has `gu` available?
