### ISSUE TITLE
jenv: version `19' is not installed

### ISSUE THREAD

**Issue by EasyG0ing1** [jenv/jenv#401]
Hello,

First of all, thank you for `jenv`, it's been the best Java SDK manager I've ever used. And everything has been moving along swimmingly for a long time now, but a few weeks ago, I did a reset on my MBP and re-installed the OS from scratch. I didn't use the migration assistant, instead, I just copied the files over that I needed and then re-installed the apps that I need from scratch, and this includes `jenv`.

Everything has been fine until a few nights ago where it's been constantly telling me this message:

`jenv: version `19' is not installed`

And it's been causing problems when I need to run maven within the Java 19 scope where I just can't get jenv to set the environment to Java 19.

I've tried everything I can think of to solve the issue including removing all jdk-19 installs including the ones inside the ~/.jenv folder then re-installing and re adding but I've not attained any success, I still keep having this problem. 

So I am asking the experts now ... what can I do to solve this problem?

Thank you,

Mike

PS - My only complaint about `jenv` is that there is no Windows version - for those times when I need to compile in Windows... ;-)

**Comment by lbilger** [comment]
Could this be related to #373? Have you tried using `19.0` instead of `19`? What's the output of `jenv versions`?

**Comment by EasyG0ing1** [comment]
@lbilger I didn't try 19.0 ... But, I haven't had any issues since replacing 19 with 19.0.2 with no straight version 19 anywhere I don't seem to be getting the error anymore.

**Comment by nicokosi** [comment]
Hello, 👋 
I had a similar issue.
Re-installing jenv with Homebrew as [documented](https://github.com/jenv/jenv#11-installing-jenv) fixed my issue: 
```sh
brew remove jenv
brew install jenv
jenv doctor
jenv enable-plugin export
```

**Comment by andrewflbarnes** [comment]
Closing per above - if you still see the issue on 0.5.7 please feel free to reopen.
