### ISSUE TITLE
jenv.be documentation is outdated: missing "enable export plugin" step

### ISSUE THREAD

**Issue by basonjui** [jenv/jenv#415]
Hi, I noticed that https://www.jenv.be is a bit outdated.

I was facing issue with mismatching versions in Maven despite setting up jenv correctly. After searching various solutions I finally found a reference to the README.md of this GitHub which shows me how to enable the export plugin and fix the issue.

Please consider update the Jenv Documentation site with this section:

> To make sure JAVA_HOME is set, make sure to enable the export plugin:
  ```bash
  jenv enable-plugin export
  exec $SHELL -l
  ```

**Comment by dre2004** [comment]
I just ran into the same issue, since this is just essentially a bunch of shell scripts it was easy find the issue. The actual command is `jenv sh-enable-plugin export`

**Comment by andrewflbarnes** [comment]
@Patterner , @dre2004 - you need to ensure `eval "$(jenv init -)"` has been run in your current shell.

The README needs correcting - the below step needs to be done regardless of whether you installed via brew/source
```
# Shell: bash
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(jenv init -)"' >> ~/.bash_profile
# Shell: zsh
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.zshrc
echo 'eval "$(jenv init -)"' >> ~/.zshrc
```

**Comment by andrewflbarnes** [comment]
The site has been updated to include enabling the export plugin :)
