### ISSUE TITLE
Terminal Start up gives ".zshrc:23: command not found: jenv"

### ISSUE THREAD

**Issue by Damesdev** [jenv/jenv#416]
I am getting a jenv command not found upon terminal start up. I can do jenv commands but still get the command not found upon startup.
.jenv does not have a bin but does have shims
My .zshrc looks like this with everything related to jenv and java:

-------------------
export PATH="/Library/java/javavirtualmachines/zulu-8.jdk/contents/home:$PATH"
export PATH="$HOME/.pyenv/versions/2.7.18/bin:$PATH"
export PATH="/opt/homebrew/Cellar/mysql-client@5.7/5.7.34/bin:$PATH"
export PATH="$HOME/.jenv/bin:$PATH"

export C_INCLUDE_PATH=/opt/homebrew/Cellar/librdkafka/2.2.0/include
export LIBRARY_PATH=/opt/homebrew/Cellar/librdkafka/2.2.0/lib

'# Enable ZSH auto-complete'
autoload -U +X compinit; compinit

'# Initialize jenv'
export JAVA_HOME="$HOME/.jenv/versions/17.0.8"
eval export PATH="$HOME/.jenv/shims:${PATH}"
eval "$(jenv init -)"
export JAVA_HOME="$HOME/.jenv/versions/17.0.8"
alias jenv_set_java_home='export JAVA_HOME="$HOME/.jenv/versions/17.0.8"'

-------------------

jenv version 0.5.6
java versions zulu-17, zulu-8
I am on M1 Mac

jenv doctor gives following respons:

-------------------
[ERROR]	JAVA_HOME variable already set, scripts that use it directly could not use java version set by jenv
[OK]	Java binaries in path are jenv shims
[ERROR]	Jenv is not loaded in your zsh
[ERROR]	To fix : 	echo eval "$(jenv init -)" >> $HOME/.zshrc
------------------

**Comment by Damesdev** [comment]
I am also using iterm2.

**Comment by andrewflbarnes** [comment]
Probably a couple of things to address here

1: setting the path shouldn't eval, it should just be
```
export PATH="$HOME/.jenv/shims:${PATH}"
```

2: you are manually seeting JAVA_HOME and don't have the export hook enabled (the first error from jenv doctor)

In an existing shell
```bash
# init jenv - should work if you can do other jenv commands
eval "$(jenv init -)"
# enable export plugin
jenv plugin-enable export
```

Then remove the `export JAVA_HOME=...` entries from your zsh_profile/zshrc and start a new terminal

3: the `eval  "$(jenv init -)"` in your zshrc (assuming this is line 23) isn't working for some reason (the second and third errors)

This might be solved just by doing the above. if not could you verify
- JENV_ROOT is not set, or set to $HOME/.jenv (per your PATH variable)
- the PATH definitely has $HOME/.jenv/bin in it at the point the eval is called
- $HOME/.jenv/bin/jenv exists
- What the exact error messages you see when starting a new zsh shell are

**Comment by Damesdev** [comment]
@andrewflbarnes I was able to solve this issue previously removed all mentions and re-installed java. I dont necessarily remember exactly what the issue was but its working currently.
