### ISSUE TITLE
jenv: no such command `enable-plugin'

### ISSUE THREAD

**Issue by fbiville** [jenv/jenv#64]
Hello, I'm facing a weird issue on my mac.
Whenever I try:

```
$> jenv enable-plugin maven                                                                                                         10:09  fbiville@VID01701
jenv: no such command `enable-plugin'
```

However, 

```
$> jenv help enable-plugin                                                                                                          10:09  fbiville@VID01701
Usage: jenv enable-plugin <pluginName>

Activate a jEnv plugin
```

What's going on?

**Comment by shweta2202** [comment]
How were you able to fix it ? 
```
ssrivastava$ jenv --version
jenv 0.2.0-20140426
ssrivastava$ jenv doctor
[OK]	No JAVA_HOME set
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correlly loaded
```

**Comment by fbiville** [comment]
I wish I remembered and wrote it out back then. Sorry!

**Comment by fbiville** [comment]
@shweta2202 you seem to run an old version of `jenv` though.

**Comment by shweta2202** [comment]
@fbiville That was it. I updated the jenv version and everything is good again. Thanks for your help!

**Comment by nekperu15739** [comment]
In my case I use brew to install _jenv_, so I didn't follow this sentence:

`$ echo 'eval "$(jenv init -)"' >> ~/.bash_profile`

executing it, solve the problem.

**Comment by nik24** [comment]
> In my case I use brew to install _jenv_, so I didn't follow this sentence:
> 
> `$ echo 'eval "$(jenv init -)"' >> ~/.bash_profile`
> 
> executing it, solve the problem.

After installing jenv via `brew install jenv`, in the output of `jenv doctor`, I could see

```
[ERROR]	Jenv is not loaded in your bash
[ERROR]	To fix : 	cat eval "$(jenv init -)" >> /Users/nikhilsahu/.bash_profile
```

The objective was to insert a line into `~/.bash_profile`
This should instead be

```
[ERROR]	To fix : 	echo 'eval "$(jenv init -)"' >> ~/.bash_profile
```

**Comment by kamal-** [comment]
check: `vi ~/.bash_profile` or `vi ~/.bashrc` file. 
See if there are single entries of `eval "$(jenv init -)"`
execute `source ~/.bash_profile` 
In my case this was happening.

**Comment by vinaypoddar1** [comment]
This resolved the problem for me

`➜  ~ eval "$(jenv init -)" >> /Users/<your-user>/.zshrc `

**Comment by zhhaojie** [comment]
```
brew install jenv
echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(jenv init -)"' >> ~/.bash_profile
source .bash_profile
cd /Library/Java/JavaVirtualMachines |ls -l
jenv add /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
jenv add /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home
jenv add /Library/Java/JavaVirtualMachines/jdk-11.0.4.jdk/Contents/Home
jenv add /Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home
jenv global 1.8.0_162
jenv enable-plugin maven
jenv enable-plugin export
exit 
javac -version
```

**Comment by davinchia** [comment]
@zhhaojie that was a very useful list!

**Comment by BitterDone** [comment]
Thank you all! For my fix, I had these lines out of order. This block:
`# ensure that JAVA_HOME is correct
jenv enable-plugin export
# make Maven aware of the Java version in use (and switch when your project does)
jenv enable-plugin maven`

must come after this block:
`export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"`

**Comment by adrian-skybaker** [comment]
Despite the hints above, this was still proving an issue for me when trying to enable the plugin from a packer script. This set of commands was resulting in `jenv: no such command `enable-plugin'`:

```
"brew install jenv",
"echo 'export PATH=\"$HOME/.jenv/bin:$PATH\"' >> ~/.bash_profile",      
"echo 'eval \"$(jenv init -)\"' >> ~/.bash_profile",      
"source ~/.bash_profile",
"jenv enable-plugin export",
```

Based on the troubleshooting at https://www.packer.io/docs/provisioners/shell#troubleshooting, it was because packer was defaulting to using `/bin/sh` which wasn't bash. Adding an explicit instruction to use bash allowed the plugin command to be recognised:

```
inline_shebang = "/bin/bash -e"
```

**Comment by adrian-skybaker** [comment]
In addition, even though the above runs the "enable-plugin" command without error, it's still not active unless a new shell is spawned, which is awkward from within an existing script.

**Comment by adamthegeek** [comment]
open the terminal and tap: eval "$(jenv init -)"

you'll get this:
![Screen Shot 2021-09-11 at 11 42 50 (2)](https://user-images.githubusercontent.com/89335972/132942194-8c6a1215-e5b4-4b60-aaf4-b4a5dc7fb38f.png)

**Comment by aalisiite** [comment]
I expierenced the same issue when wrote in console "jenv doctor", nothing helped until I used "eval "$(jenv init -)"". Spent like 8 hours on this.
