### ISSUE TITLE
no such command `shell'

### ISSUE THREAD

**Issue by paul-hammant** [jenv/jenv#80]
$> jenv --help 
jenv 0.4.0
Usage: jenv <command> [<args>]

Some useful jenv commands are:
   commands    List all available jenv commands
   local       Set or show the local application-specific Java version
   global      Set or show the global Java version
   shell       Set or show the shell-specific Java version
   .........

$> jenv shell 1.7
jenv: no such command `shell'

**Comment by gcuisinier** [comment]
Could you provide output of

```jenv doctor```

**Comment by davidxia** [comment]
Just tried out jenv. Seems pretty cool. I got the same error on Mac OS X 10.10.4, installed via homebrew, jenv 0.4.3:

```
bash-3.2$ jenv --help

jenv 0.4.3
Usage: jenv <command> [<args>]

Some useful jenv commands are:
   commands    List all available jenv commands
   local       Set or show the local application-specific Java version
   global      Set or show the global Java version
   shell       Set or show the shell-specific Java version
   rehash      Rehash jenv shims (run this after installing executables)
   version     Show the current Java version and its origin
   versions    List all Java versions available to jenv
   which       Display the full path to an executable
   whence      List all Java versions that contain the given executable

See `jenv help <command>' for information on a specific command.
For full documentation, see: https://github.com/hikage/jenv#readme

bash-3.2$ jenv shell oracle64-1.8.0.31

jenv: no such command `shell'
bash-3.2$ jenv doctor
[ERROR]	JAVA_HOME variable already set, scripts that use it directly could not use java version set by jenv
[ERROR]	Java binary in path is not in the jenv shims.
[ERROR]	Please check your path, or try using /path/to/java/home is not a valid path to java installation.
	PATH : /usr/local/Cellar/jenv/0.4.3/libexec/libexec:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/munki:/Users/dxia/google-cloud-sdk/bin:/Users/dxia/.rvm/bin
[ERROR]	Jenv is not loaded in your fish
[ERROR]	To fix : 	cat eval "$(jenv init -)" >> your profile

bash-3.2$ eval $(jenv init -)

bash: syntax error near unexpected token `('

bash-3.2$ jenv init -

export PATH="/Users/dxia/.jenv/shims:${PATH}"
jenv rehash 2>/dev/null
export JENV_LOADED=1
unset JAVA_HOME
jenv() {
  typeset command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  enable-plugin|rehash|shell|shell-options)
    eval `jenv "sh-$command" "$@"`;;
  *)
    command jenv "$command" "$@";;
  esac
}
```

**Comment by haifzhan** [comment]
same issue! any idea?

**Comment by gvlamadrid** [comment]
+1

JAVA_HOME=/usr/local/var/jenv/versions/1.7.0.80

[ERROR]	JAVA_HOME variable already set, scripts that use it directly could not use java version set by jenv
[OK]	Java binaries in path are jenv shims
[OK]	Jenv is correctly loaded

**Comment by kbzod** [comment]
I had this same problem. It was because I was using a non-login bash shell (via https://github.com/jamesob/desk), and `jenv init -` was being evaluated in ~/.bash_profile. Running `jenv init -` establishes the jenv shell function, which makes `jenv shell` work. A non-login shell won't run .bash_profile, though, and so `jenv` ends up pointing to the actual jenv script, which doesn't handle it.

**Comment by gcuisinier** [comment]
@kbzod thanks for the tips, I will try to reproduce.

**Comment by bhagatparwinder** [comment]
Slight variation of the issue.
`jenv shell oracle64-1.7.0.79` works absolutely fine but running the same command from a .command file does not. I have created scripts that do the build and deploy process for my applications. These applications use diff Java versions and I'm trying to set it using jenv in the script.

**Comment by dotCipher** [comment]
Having the same issue here after:
`brew install jenv`
then running jenv in `fish`.

**Comment by davidxia** [comment]
Not sure what changed, but this works for me now with the below versions and settings.

```
brew info jenv

jenv: stable 0.4.4, HEAD
Manage your Java environment
https://www.jenv.be/
/usr/local/Cellar/jenv/0.4.4 (78 files, 65.5KB) *
  Built from source on 2018-05-17 at 22:06:52
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/jenv.rb
==> Options
--HEAD
	Install HEAD version

fish --version

fish, version 2.7.1
```

I also copied jenv.fish and export.fish to my fish config dir as stated [here](https://github.com/gcuisinier/jenv#gettings-started).

**Comment by kmoschcau** [comment]
Hi. I just tried this in fish and the `shell` subcommand mostly works. The only issue I have with it is that the `--unset` option does not work, because it tries to unset the environment variable with `unset`, which will of course not work. In fish you would have to use `set -e` instead.

**Comment by lucasveljacic** [comment]
The suggestion made by `jenv doctor` command did the trick for me.

`[ERROR] To fix :    echo eval "$(jenv init -)" >> /Users/user.name/.bash_profile`

Thanks!

**Comment by andrewflbarnes** [comment]
Closing as stale.

@kmoschcau - #435 has been created to address the unset problem
